// In-memory fixture dataset. Used when NEXT_PUBLIC_SUPABASE_URL /
// NEXT_PUBLIC_SUPABASE_ANON_KEY are absent, so the desk runs and renders
// with zero external setup. The numbers are chosen so that the canonical
// `underwrite()` math (arv*0.7 - repairs - asking) yields the verdict stored
// on each underwrite row — the desk never invents its own math.
import type {
  Buyer,
  Contract,
  Deal,
  Match,
  Owner,
  Property,
  Underwrite,
} from "@parcel/types";

// Use the current month so the dashboard "this month" pace metric lights up
// regardless of when the fixtures are read.
const now = new Date();
const iso = (dayOffset: number, hour = 9): string => {
  const d = new Date(now.getFullYear(), now.getMonth(), 1 + dayOffset, hour);
  return d.toISOString();
};

export const properties: Property[] = [
  {
    id: "prop-1",
    source: "attom",
    source_id: "ATT-44821",
    address: "1420 Beckwith Ave",
    city: "Missoula",
    state: "MT",
    zip: "59801",
    lat: 46.86,
    lng: -114.02,
    beds: 3,
    baths: 2,
    sqft: 1480,
    year_built: 1968,
    est_value: 365000,
    asking: 250000,
    distress_signals: ["absentee", "tax_delinquent"],
    created_at: iso(1),
  },
  {
    id: "prop-2",
    source: "batchdata",
    source_id: "BD-90112",
    address: "78 Strand Ave",
    city: "Missoula",
    state: "MT",
    zip: "59801",
    lat: 46.87,
    lng: -114.0,
    beds: 4,
    baths: 2,
    sqft: 1920,
    year_built: 1955,
    est_value: 420000,
    asking: 295000,
    distress_signals: ["preforeclosure"],
    created_at: iso(2),
  },
  {
    id: "prop-3",
    source: "attom",
    source_id: "ATT-51190",
    address: "905 Defoe St",
    city: "Missoula",
    state: "MT",
    zip: "59802",
    lat: 46.88,
    lng: -113.99,
    beds: 2,
    baths: 1,
    sqft: 980,
    year_built: 1942,
    est_value: 290000,
    asking: 215000,
    distress_signals: ["vacant"],
    created_at: iso(3),
  },
  {
    id: "prop-4",
    source: "manual",
    source_id: null,
    address: "311 Wylie Ave",
    city: "Bozeman",
    state: "MT",
    zip: "59715",
    lat: 45.68,
    lng: -111.04,
    beds: 5,
    baths: 3,
    sqft: 2600,
    year_built: 1978,
    est_value: 610000,
    asking: 480000,
    distress_signals: ["absentee"],
    created_at: iso(4),
  },
  {
    id: "prop-5",
    source: "batchdata",
    source_id: "BD-77310",
    address: "44 Cooper St",
    city: "Bozeman",
    state: "MT",
    zip: "59718",
    lat: 45.67,
    lng: -111.06,
    beds: 3,
    baths: 2,
    sqft: 1650,
    year_built: 1989,
    est_value: 455000,
    asking: 372000,
    distress_signals: ["tax_delinquent"],
    created_at: iso(6),
  },
  {
    id: "prop-6",
    source: "attom",
    source_id: "ATT-60044",
    address: "12 Rattlesnake Dr",
    city: "Missoula",
    state: "MT",
    zip: "59802",
    lat: 46.9,
    lng: -113.98,
    beds: 4,
    baths: 3,
    sqft: 2200,
    year_built: 2001,
    est_value: 540000,
    asking: 430000,
    distress_signals: ["absentee", "vacant"],
    created_at: iso(8),
  },
];

export const owners: Owner[] = [
  {
    id: "own-1",
    property_id: "prop-1",
    full_name: "Dana Whitfield",
    email: "dana.w@example.com",
    phone: "406-555-0142",
    mailing_address: "PO Box 221, Missoula, MT 59806",
    skiptrace_status: "matched",
    skiptrace_confidence: 0.88,
    created_at: iso(1),
  },
  {
    id: "own-2",
    property_id: "prop-2",
    full_name: "Raymond Ostler",
    email: "rayost@example.com",
    phone: "406-555-0199",
    mailing_address: "78 Strand Ave, Missoula, MT 59801",
    skiptrace_status: "matched",
    skiptrace_confidence: 0.74,
    created_at: iso(2),
  },
  {
    id: "own-3",
    property_id: "prop-3",
    full_name: "Lena Cho",
    email: null,
    phone: "406-555-0173",
    mailing_address: null,
    skiptrace_status: "matched",
    skiptrace_confidence: 0.61,
    created_at: iso(3),
  },
  {
    id: "own-4",
    property_id: "prop-4",
    full_name: "Marcus Boyd",
    email: "mboyd@example.com",
    phone: "406-555-0120",
    mailing_address: "9 Birchwood Ln, Bozeman, MT 59715",
    skiptrace_status: "matched",
    skiptrace_confidence: 0.91,
    created_at: iso(4),
  },
  {
    id: "own-5",
    property_id: "prop-5",
    full_name: "Tasha Reyes",
    email: "treyes@example.com",
    phone: null,
    mailing_address: "44 Cooper St, Bozeman, MT 59718",
    skiptrace_status: "matched",
    skiptrace_confidence: 0.69,
    created_at: iso(6),
  },
  {
    id: "own-6",
    property_id: "prop-6",
    full_name: "Owner pending",
    email: null,
    phone: null,
    mailing_address: null,
    skiptrace_status: "pending",
    skiptrace_confidence: null,
    created_at: iso(8),
  },
];

// underwrite math (rule 0.70, fee_target 12000):
//   buyer_ceiling = arv*0.70 - repairs
//   your_mao      = buyer_ceiling - 12000
//   fee_potential = buyer_ceiling - asking
//   verdict       = fee_potential >= 12000 ? clear : fee_potential > 0 ? thin : pass
export const underwrites: Underwrite[] = [
  {
    // arv 365000, repairs 30000 -> ceiling 225500; asking 250000 -> fee -24500 (pass)
    id: "uw-1",
    property_id: "prop-1",
    arv: 365000,
    repairs: 30000,
    rule_pct: 0.7,
    fee_target: 12000,
    buyer_ceiling: 225500,
    your_mao: 213500,
    fee_potential: -24500,
    is_estimate: false,
    verdict: "pass",
    created_at: iso(1),
  },
  {
    // arv 420000, repairs 18000 -> ceiling 276000; asking 295000 -> fee -19000 (pass)
    id: "uw-2",
    property_id: "prop-2",
    arv: 420000,
    repairs: 18000,
    rule_pct: 0.7,
    fee_target: 12000,
    buyer_ceiling: 276000,
    your_mao: 264000,
    fee_potential: -19000,
    is_estimate: false,
    verdict: "pass",
    created_at: iso(2),
  },
  {
    // arv 340000, repairs 22000 -> ceiling 216000; asking 215000 -> fee 1000 (thin)
    id: "uw-3",
    property_id: "prop-3",
    arv: 340000,
    repairs: 22000,
    rule_pct: 0.7,
    fee_target: 12000,
    buyer_ceiling: 216000,
    your_mao: 204000,
    fee_potential: 1000,
    is_estimate: true,
    verdict: "thin",
    created_at: iso(3),
  },
  {
    // arv 720000, repairs 35000 -> ceiling 469000; asking 480000 -> fee -11000 (pass)
    id: "uw-4",
    property_id: "prop-4",
    arv: 720000,
    repairs: 35000,
    rule_pct: 0.7,
    fee_target: 12000,
    buyer_ceiling: 469000,
    your_mao: 457000,
    fee_potential: -11000,
    is_estimate: false,
    verdict: "pass",
    created_at: iso(4),
  },
  {
    // arv 580000, repairs 20000 -> ceiling 386000; asking 372000 -> fee 14000 (clear)
    id: "uw-5",
    property_id: "prop-5",
    arv: 580000,
    repairs: 20000,
    rule_pct: 0.7,
    fee_target: 12000,
    buyer_ceiling: 386000,
    your_mao: 374000,
    fee_potential: 14000,
    is_estimate: false,
    verdict: "clear",
    created_at: iso(6),
  },
  {
    // arv 660000, repairs 18000 -> ceiling 444000; asking 430000 -> fee 14000 (clear)
    id: "uw-6",
    property_id: "prop-6",
    arv: 660000,
    repairs: 18000,
    rule_pct: 0.7,
    fee_target: 12000,
    buyer_ceiling: 444000,
    your_mao: 432000,
    fee_potential: 14000,
    is_estimate: true,
    verdict: "clear",
    created_at: iso(8),
  },
];

export const deals: Deal[] = [
  { id: "deal-1", property_id: "prop-1", stage: "Lead", assigned_buyer_id: null, notes: "Tax lien filed 2024; absentee owner out of state.", created_at: iso(1) },
  { id: "deal-2", property_id: "prop-2", stage: "Contacted", assigned_buyer_id: null, notes: "Sent intro offer letter, awaiting reply.", created_at: iso(2) },
  { id: "deal-3", property_id: "prop-3", stage: "Lead", assigned_buyer_id: null, notes: "Vacant, marginal spread — watch.", created_at: iso(3) },
  { id: "deal-4", property_id: "prop-4", stage: "Contacted", assigned_buyer_id: null, notes: "Owner replied 'maybe', following up.", created_at: iso(4) },
  { id: "deal-5", property_id: "prop-5", stage: "Under contract", assigned_buyer_id: null, notes: "Verbal yes at $372k. Contract queued.", created_at: iso(6) },
  { id: "deal-6", property_id: "prop-6", stage: "Assigned", assigned_buyer_id: "buyer-1", notes: "Assigned to Summit Holdings at $444k ceiling.", created_at: iso(9) },
];

export const buyers: Buyer[] = [
  {
    id: "buyer-1",
    name: "Summit Holdings",
    type: "flipper",
    min_price: 200000,
    max_price: 500000,
    min_beds: 3,
    areas: ["Missoula", "Bozeman"],
    max_repairs: 40000,
    notes: "Cash, closes in 14 days. Prefers absentee.",
    email: "acq@summitholdings.example.com",
    phone: "406-555-0301",
    created_at: iso(0),
  },
  {
    id: "buyer-2",
    name: "Bitterroot Rentals",
    type: "buy_and_hold",
    min_price: 150000,
    max_price: 350000,
    min_beds: 2,
    areas: ["Missoula"],
    max_repairs: 25000,
    notes: "Wants rent-ready or light rehab only.",
    email: "deals@bitterrootrentals.example.com",
    phone: "406-555-0302",
    created_at: iso(0),
  },
  {
    id: "buyer-3",
    name: "Gallatin Capital",
    type: "flipper",
    min_price: 300000,
    max_price: 800000,
    min_beds: 3,
    areas: ["Bozeman"],
    max_repairs: 60000,
    notes: "Bozeman only, larger projects OK.",
    email: "buy@gallatincapital.example.com",
    phone: "406-555-0303",
    created_at: iso(0),
  },
];

export const matches: Match[] = [
  { deal_id: "deal-5", buyer_id: "buyer-1", score: 92, qualifies: true, sent_at: null },
  { deal_id: "deal-5", buyer_id: "buyer-3", score: 81, qualifies: true, sent_at: null },
  { deal_id: "deal-6", buyer_id: "buyer-1", score: 88, qualifies: true, sent_at: iso(9) },
  { deal_id: "deal-6", buyer_id: "buyer-3", score: 79, qualifies: true, sent_at: null },
];

export const contracts: Contract[] = [
  {
    id: "ctr-1",
    property_id: "prop-5",
    owner_id: "own-5",
    buyer_id: null,
    offer_price: 372000,
    pdf_url: null,
    status: "queued",
    created_at: iso(6),
  },
  {
    id: "ctr-2",
    property_id: "prop-6",
    owner_id: "own-6",
    buyer_id: "buyer-1",
    offer_price: 430000,
    pdf_url: "https://example.com/contracts/ctr-2.pdf",
    status: "sent",
    created_at: iso(9),
  },
];
